spring:
  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT:localhost}:3306/portfolio?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true
#    url: jdbc:mysql://localhost:3306/portfolio?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: portfolio_user
    password: ${RDS_PASSWORD:portfolio1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        session_factory:
          statement_inspector: ding.co.backendportfolio.chapter5.config.QueryCountInspector
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework: info

jwt:
  secret: your-256-bit-secret-your-256-bit-secret-your-256-bit-secret-your-256-bit-secret
  token-validity-in-seconds: 86400  # 24시간

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,info,prometheus"  # prometheus 추가
  endpoint:
    health:
      show-details: always  # 상세한 헬스 정보 표시

server:
  tomcat:
    connection-timeout: 120000      # 120초
  servlet:
    session:
      timeout: 120s                # 세션 타임아웃
