spring:
  datasource:
    url: jdbc:mysql://portfolio-db.cz8sc4a0qheo.ap-northeast-2.rds.amazonaws.com:3306/portfolio?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: portfolio_user
    password: your-actual-password
    driver-class-name: com.mysql.cj.jdbc.Driver